name: Canary versions Test

on:
  push:
    branches:
      - pr-mirror-url

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest, macos-13, ubuntu-24.04-arm]
     
    steps:
      - uses: actions/checkout@v4
      - uses: aparnajyothi-y/setup-node@add-mirror-url
        with:
          node-version: '20.0.0-v8-canary'
          mirror-url: 'https://mirrors.dotsrc.org/nodejs/v8-canary/'
      - name: Verify Node.js installation
        run: node -v    
      - run: npm i
     
