name: check-latest Test

on:
  push:
    branches:
      - pr-mirror-url

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest, macos-13]
     
    steps:
      - uses: actions/checkout@v4
      - uses: aparnajyothi-y/setup-node@add-mirror-url
        with:
          node-version: '18'
          mirror-url: http://download.redis.io/releases/
          check-latest: true
      - name: Verify Node.js installation
        run: node -v    
      - run: npm ci
     
