name: Test with HTTP Protocol Mirror url
on:
  workflow_dispatch:
  push:
    branches:
      - pr-mirror-url

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest, macos-13, ubuntu-24.04-arm]
     
    steps:
      - uses: actions/checkout@v4
      - uses: marco-ippolito/setup-node@mirror
        with:
          node-version: '20'
          mirror-url: 'http://mirrors.dotsrc.org/nodejs/release/'
      - name: Verify Node.js installation
        run: node -v   
      - run: npm i
     
