name: Test with Invalid URL

on:
  workflow_dispatch:
  push:
    branches:
      - pr-test-1240-mirror

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest, macos-13, ubuntu-24.04-arm]
     
    steps:
      - uses: actions/checkout@v4
      - uses: marco-ippolito/setup-node@mirror
        with:
          node-version: '16'
          mirror: 'https://mirror.yandex.ru/mirrors/nodejs.org/'
          mirror-token: ${{secrets.GITHUB_TOKEN}}

      - name: Verify Node.js installation
        run: node -v
      - run: npm i
     
  test-non-lts:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest, macos-13, ubuntu-24.04-arm]
     
    steps:
      - uses: actions/checkout@v4
      - uses: marco-ippolito/setup-node@mirror
        with:
          node-version: '17'
          mirror: 'https://mirror.yandex.ru/mirrors/nodejs.org/'
          mirror-token: ${{secrets.GITHUB_TOKEN}}
          
      - name: Verify Node.js installation
        run: node -v
      - run: npm i
     
