name: Nightly versions Test

on:
  push:
    branches:
      - pr-mirror-url

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest, macos-13]
     
    steps:
      - uses: actions/checkout@v4
      - uses: aparnajyothi-y/setup-node@add-mirror-url
        with:
          node-version: '16-nightly'
          mirror-url: 'https://mirrors.dotsrc.org/nodejs/nightly/'
      - name: Verify Node.js installation
        run: node -v    
      - run: npm i
     
