name: NVM LTS syntax Test

on:
  push:
    branches:
      - pr-mirror-url

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest, macos-13, ubuntu-24.04-arm]
        node-version: ['lts/erbium', 'lts/fermium', 'lts/*', 'lts/-n']  
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: aparnajyothi-y/setup-node@add-mirror-url
        with:
          node-version: ${{ matrix.node-version }}
          mirror-url: 'http://mirrors.dotsrc.org/nodejs/release/'

      - name: Verify Node.js Installation
        run: |
          node -v
          npm -v