name: NVM LTS syntax Test

on:
  push:
    branches:
      - pr-mirror-url

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest, macos-13, ubuntu-24.04-arm]
        node-version: [lts/erbium, lts/fermium, lts/*, lts/-n]  
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: marco-ippolito/setup-node@mirror
        with:
          node-version: ${{ matrix.node-version }}
          mirror: 'https://nodejs.org/dist/dist'
          mirror-token: ${{secrets.GITHUB_TOKEN}}
          

      - name: Verify Node.js Installation
        run: |
          node -v
          npm -v