name: RC versions Test

on:
  workflow_dispatch:
  push:
    branches:
      - pr-test-1240-mirror

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
     
    steps:
      - uses: actions/checkout@v4
      - uses: marco-ippolito/setup-node@mirror
        with:
          node-version: '16.0.0-rc.3'
          architecture: 'x86'
          mirror: 'https://unofficial-builds.nodejs.org/'
          mirror-token: ${{secrets.GITHUB_TOKEN}}
      - name: Verify Node.js installation
        run: node -v    
   

  test-non-lts:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest, macos-13, ubuntu-24.04-arm]
     
    steps:
      - uses: actions/checkout@v4
      - uses: marco-ippolito/setup-node@mirror
        with:
          node-version: 'v15.7.0-rc.0'
          architecture: 'x86'
          mirror: 'https://unofficial-builds.nodejs.org/'
          mirror-token: ${{secrets.GITHUB_TOKEN}}
      - name: Verify Node.js installation
        run: node -v    
      
